[build]
  command = "npm run build"
  publish = "dist"
  [build.environment]
    NODE_VERSION = "20.17.0"
    NPM_VERSION = "10.8.3"

[functions]
  node_bundler = "esbuild"

[[scheduled]]
  function = "send-deal-notifications"
  cron = "0 9 * * 1"  # Every Monday at 9 AM UTC
